### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by Fishos** [Suleman-Elahi/Cancel_Instagram_Follow_Requests#1]
HI there, 

I did everything like it should be done. The list of open follow request can be made, but then the following error occurs: 

DevTools listening on ws://127.0.0.1:51320/devtools/browser/402e458d-6e1c-4af1-a835-7fc1e1fbbb97
Got the users you have sent follow request in "follow_req.txt" file, now exiting browser...
Traceback (most recent call last):
  File "C:.....AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 523, in _call_api
    respo......nse = self.opener.open(req, timeout=self.timeout)
  File "C:\Users\..........\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\..........\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\......\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\......\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cancel_req.py", line 4, in <module>
    api = Client(loginInfo.username, loginInfo.password)
  File "C:\Users\......\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 208, in __init__
    self.login()
  File "C:\Users\......\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\endpoints\accounts.py", line 49, in login
    login_response = self._call_api(
  File "C:\Users\......\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Users\.......\AppData\Local\Programs\Python\Python38\lib\site-packages\instagram_private_api\errors.py", line 123, in process
    raise error_info['error'](
instagram_private_api.errors.ClientCheckpointRequiredError: checkpoint_challenge_required

C:\Users\.........\AppData\Local\Programs\Python\Python38>python get_follow_req.py

DevTools listening on ws://127.0.0.1:51426/devtools/browser/93fa16e5-b571-4f4e-b4b3-33af999cd194
Got the users you have sent follow request in "follow_req.txt" file, now exiting browser...

Could you tell me what I should do? Is this a bug of the app/ insta that blocked it? 

Kind regards, 

Fish

**Comment by Suleman-Elahi** [comment]
The script is working fine on my PC. Can you tell me about your Python, Chrome, and Chrome driver version?

**Comment by Fishos** [comment]
I have Python38
chrome 84.0.4147.135 (Officiële build) (64-bits)

and I use the 84.0.4147.30 chromedriver

You were right, the intial chrome driver was a newer version

The Chromedriver and the chrome browser version should be equal.

**Comment by Suleman-Elahi** [comment]
If it is not working then you can use the Andriod app: https://play.google.com/store/apps/details?id=cancel.follow.request.forinstagram&hl=en_IN
