### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Fishos** [Suleman-Elahi/Cancel_Instagram_Follow_Requests#2]
my first try with an account with 30 open follow request to cancel was succesfull. 

now i' m trying to do the manipulation with an other account which has a lot of open follow requests. 
After some time of building the account list, the python app clicks on the menu button which makes the process stop: 

DevTools listening on ws://127.0.0.1:54153/devtools/browser/f00ce7b0-bd58-4f39-8125-24c84055d644
Traceback (most recent call last):
  File "get_follow_req.py", line 38, in <module>
    vm_button.click()
  File "C:\Users\.....\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\.....\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP yWX7d    y3zKF     " type="button">...</button> is not clickable at point (880, 26). Other element would receive the click: <div class="wgVJm" role="none"></div>
  (Session info: chrome=84.0.4147.135)

Same config and install numbers as the previous posted issue. 

Could you help me out? 

with the tiny account everything went well. The big accounts stops, before trying to delete the accounts.

**Comment by Suleman-Elahi** [comment]
Can you send a screen share of the scenario? How may sent requests are there?
